/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerComponentsRouteImport } from './routes/server-components'
import { Route as ServerFunctionsRouteImport } from './routes/server-functions'
import { Route as SsrRouteImport } from './routes/ssr'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerComponentsRoute = ServerComponentsRouteImport.update({
  id: '/server-components',
  path: '/server-components',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerFunctionsRoute = ServerFunctionsRouteImport.update({
  id: '/server-functions',
  path: '/server-functions',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrRoute = SsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/server-components': typeof ServerComponentsRoute
  '/server-functions': typeof ServerFunctionsRoute
  '/ssr': typeof SsrRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/server-components': typeof ServerComponentsRoute
  '/server-functions': typeof ServerFunctionsRoute
  '/ssr': typeof SsrRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/server-components': typeof ServerComponentsRoute
  '/server-functions': typeof ServerFunctionsRoute
  '/ssr': typeof SsrRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/server-components' | '/server-functions' | '/ssr' | '/api/health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/server-components' | '/server-functions' | '/ssr' | '/api/health'
  id:
    | '__root__'
    | '/'
    | '/server-components'
    | '/server-functions'
    | '/ssr'
    | '/api/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServerComponentsRoute: typeof ServerComponentsRoute
  ServerFunctionsRoute: typeof ServerFunctionsRoute
  SsrRoute: typeof SsrRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-components': {
      id: '/server-components'
      path: '/server-components'
      fullPath: '/server-components'
      preLoaderRoute: typeof ServerComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-functions': {
      id: '/server-functions'
      path: '/server-functions'
      fullPath: '/server-functions'
      preLoaderRoute: typeof ServerFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr': {
      id: '/ssr'
      path: '/ssr'
      fullPath: '/ssr'
      preLoaderRoute: typeof SsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServerComponentsRoute: ServerComponentsRoute,
  ServerFunctionsRoute: ServerFunctionsRoute,
  SsrRoute: SsrRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
